apiVersion: v1
kind: Pod
metadata:
  name: dbz-connect
  namespace: ns-dbz-data-engineer
  labels:
    app: dbz-connect
spec:
  containers:
  - name: dbz-connect
    image: debezium/connect:1.9
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"
    env:
      - name: CONFIG_STORAGE_TOPIC
        value: 'dbz.connect.configs'
      - name: OFFSET_STORAGE_TOPIC
        value: 'dbz.connect.offsets'
      - name: STATUS_STORAGE_TOPIC
        value: 'dbz.connect.statuses'
      - name: BOOTSTRAP_SERVERS
        value: 'kafka-svc.ns-dbz-data-engineer.svc.cluster.local:9092'
    ports:
      - containerPort: 8083
