apiVersion: v1
kind: ConfigMap
metadata:
  name: job-include-postgres-connector-cm
  namespace: ns-dbz-data-engineer
data:
  parameters.json: |    
    {
      "name": "postgres-connector",
      "config": {
        "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
        "database.hostname": "postgres-svc.ns-dbz-data-engineer.svc.cluster.local",
        "database.port": "5432",
        "database.user": "postgres",
        "database.password": "postgres",
        "database.dbname" : "debezium_db",
        "database.server.name": "postgres",
        "table.include.list": "public.CUSTOMERS",
        "plugin.name": "pgoutput"
      }
    }