apiVersion: v1
kind: Service
metadata:
  name: dbz-connect-svc
  namespace: ns-dbz-data-engineer
spec:
  selector:
    app: dbz-connect
  ports:
    - name: connect
      port: 8083
      targetPort: 8083
