apiVersion: v1
kind: Pod
metadata:
  name: dbz-kafka-ui
  namespace: ns-dbz-data-engineer
  labels:
    app: kafka-ui
spec:
  containers:
  - name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"
    env:
      - name: DYNAMIC_CONFIG_ENABLED
        value: 'true'
      - name: KAFKA_CLUSTERS_0_NAME
        value: 'dbz-test'
      - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
        value: 'kafka-svc.ns-dbz-data-engineer.svc.cluster.local:9092'
    ports:
      - containerPort: 8080
