apiVersion: v1
kind: Pod
metadata:
  name: dbz-kafka
  namespace: ns-dbz-data-engineer
  labels:
    app: kafka
spec:
  containers:
  - name: kafka1
    image: wurstmeister/kafka
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"
    env:
      - name: KAFKA_BROKER_ID
        value: '1'
      - name: KAFKA_ZOOKEEPER_CONNECT
        value: 'zk-svc.ns-dbz-data-engineer.svc.cluster.local:2181'
      - name: KAFKA_LISTENERS
        value: 'INTERNAL://:29092,EXTERNAL://:9092'
      - name: KAFKA_ADVERTISED_LISTENERS
        value: 'INTERNAL://dbz-kafka:29092,EXTERNAL://kafka-svc.ns-dbz-data-engineer.svc.cluster.local:9092'
      - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        value: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      - name: KAFKA_INTER_BROKER_LISTENER_NAME
        value: 'INTERNAL'
    ports:
      - containerPort: 9092