apiVersion: v1
kind: Pod
metadata:
  name: dbz-postgres
  namespace: ns-dbz-data-engineer
  labels:
    app: postgres
spec:
  volumes:
    - name: data-postgres
      persistentVolumeClaim:
        claimName: postgres-pvc
  containers:
  - name: postgres
    image: postgres:15.2-alpine
    args: [ "postgres", "-c", "wal_level=logical" ]
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"        
    env:
      - name: POSTGRES_PASSWORD
        value: 'postgres'      
      - name: POSTGRES_DB
        value: 'debezium_db'      
    ports:
      - containerPort: 5432
    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: data-postgres
