apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: ns-dbz-data-engineer
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
