apiVersion: v1
kind: Pod
metadata:
  name: dbz-zk
  namespace: ns-dbz-data-engineer
  labels:
    app: zk
spec:
  containers:
  - name: zookeeper
    image: zookeeper:latest
    resources:
      limits:
        memory: "500Mi"
        cpu: "500m"
    env:
      - name: ZOOKEEPER_CLIENT_PORT
        value: '2181'
      - name: ZOOKEEPER_TICK_TIME
        value: '2000'
    ports:
      - containerPort: 2181      
