apiVersion: v1
kind: Service
metadata:
  name: zk-svc
  namespace: ns-dbz-data-engineer
spec:
  type: ClusterIP
  selector:
    app: zk
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181    